//This document is automatically generated by the SPS parser and will be refreshed every time SPDF is started. 
//Any changes you make will not be saved.
//此文档由SPS解析器自动生成，每次启动SPDF之前此文件都会被刷新。
//您的任何更改都不会保存。
export function syn_SPOL() {}

syn_SPOL.__head__ = 
[""];//0
SPDF.preloadStory("syn.__head__",syn_SPOL.__head__);

syn_SPOL.PartA = 
[">>>青雅音/2/3//1:???:3333>>>T2:ssss", //0
"SWITCH 2", //1
"    CASE 1", //2
"        >>>:\"Hello World 1\"", //3
"    CASE 2", //4
"        >>>:\"Hello World 2#3333\" ", //5
"        SWITCH 5", //6
"            CASE 4", //7
"                >>>:\"Hello World 2-4\"", //8
"            CASE 5", //9
"                >>>:\"Hello World 2-5\"", //10
"                SWITCH 1", //11
"                    CASE 1", //12
"                        >>>:\"Hello World 2-5-1\"", //13
"                    CASE 2", //14
"                        >>>:\"Hello World 2-5-2\"", //15
"    CASE 3", //16
"        >>>:\"Hello World 3\"", //17
">>>:\"Hello World 0\"", //18
"", //19
""];//20
SPDF.preloadStory("syn.PartA",syn_SPOL.PartA);

syn_SPOL.PartB = 
[">>>罗德岛干员//1:后勤部干员A:昨天的月末后勤满意度调查情况如何？>>>罗德岛干员:", //0
">>>罗德岛干员//1:>>>罗德岛干员:后勤部干员B:总的来说还不错，但是......但是博士一直在跟我们抱怨这个月的空调系统是不是有毛病", //1
">>>罗德岛干员//1:后勤部干员A:空调系统？空调系统可是上个月月末刚刚彻底检修过一遍的。>>>罗德岛干员:", //2
">>>罗德岛干员//1:后勤部干员A:博士房间的门在罗德岛行进过程中自己颠开的概率都比空调系统出问题的概率大吧？", //3
">>>可露希尔:我听说有人在抱怨空调系统？", //4
">>>罗德岛干员//1:后勤部干员A:啊，是可总师！", //5
">>>可露希尔:所以到底是什么情况？", //6
">>>罗德岛干员//1:后勤部干员B:博士说过去一个月空调系统的情况都不能让他满意，我们暂不清楚是什么情况，需要我们去调查一下么？", //7
">>>可露希尔:博士？", //8
""];//9
SPDF.preloadStory("syn.PartB",syn_SPOL.PartB);

