//This document is automatically generated by the SPS parser and will be refreshed every time SPDF is started. 
//Any changes you make will not be saved.
//此文档由SPS解析器自动生成，每次启动SPDF之前此文件都会被刷新。
//您的任何更改都不会保存。
export function syn_SPOL() {}

syn_SPOL.__head__ = 
[""];
SPDF.preloadStory("SPDF.resource.syn.__head__",syn_SPOL.__head__);

syn_SPOL.PartA = 
["SWITCH 2", 
"    CASE 1", 
"        >>>:\"Hello World 1\"", 
"    CASE 2", 
"        >>>:\"Hello World 2\"", 
"        SWITCH 5", 
"            CASE 4", 
"                >>>:\"Hello World 2-4\"", 
"            CASE 5", 
"                >>>:\"Hello World 2-5\"", 
"                SWITCH 1", 
"                    CASE 1", 
"                        >>>:\"Hello World 2-5-1\"", 
"                    CASE 2", 
"                        >>>:\"Hello World 2-5-2\"", 
"    CASE 3", 
"        >>>:\"Hello World 3\"", 
">>>:\"Hello World 0\"", 
"", 
""];
SPDF.preloadStory("SPDF.resource.syn.PartA",syn_SPOL.PartA);

